Repository dabeann/dorandoran, pull requests merged in 2024-06, with the labels that each got.

#35 Refactor/counsel
  src/main/java/com/backend/dorandoran/contents/controller/ContentsController.java
  src/main/java/com/backend/dorandoran/contents/repository/PsychotherapyContentsRepository.java
  src/main/java/com/backend/dorandoran/contents/repository/querydsl/PsychotherapyContentsQueryRepository.java
  src/main/java/com/backend/dorandoran/contents/repository/querydsl/PsychotherapyContentsQueryRepositoryImpl.java
  src/main/java/com/backend/dorandoran/contents/service/ContentsService.java
  src/main/java/com/backend/dorandoran/counsel/controller/CounselController.java
  src/main/java/com/backend/dorandoran/counsel/domain/entity/Counsel.java
  src/main/java/com/backend/dorandoran/counsel/domain/request/ChatRequest.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselService.java
Labels: :recycle: refactor

#36 Refactor/counsel
  src/main/java/com/backend/dorandoran/common/domain/Disease.java
  src/main/java/com/backend/dorandoran/common/domain/counsel/CounselState.java
  src/main/java/com/backend/dorandoran/contents/controller/ContentsController.java
  src/main/java/com/backend/dorandoran/contents/service/ContentsService.java
  src/main/java/com/backend/dorandoran/counsel/controller/CounselController.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselService.java
Labels: :recycle: refactor

#37 feat: add message date
  src/main/java/com/backend/dorandoran/counsel/domain/response/DialogHistory.java
Labels: :sparkles: feature

#47 Refactor/python to java 상담 채팅 기능
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  src/main/java/com/backend/dorandoran/common/domain/ErrorCode.java
  src/main/java/com/backend/dorandoran/config/GptConfig.java
  src/main/java/com/backend/dorandoran/counsel/controller/CounselController.java
  src/main/java/com/backend/dorandoran/counsel/domain/entity/Counsel.java
  src/main/java/com/backend/dorandoran/counsel/repository/CounselRepository.java
  src/main/java/com/backend/dorandoran/counsel/repository/DialogRepository.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselChatService.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselService.java
Labels: :recycle: refactor

#50 Refactor/python to java
  .github/workflows/deploy.yml
  src/main/java/com/backend/dorandoran/common/domain/BaseDateTimeEntity.java
  src/main/java/com/backend/dorandoran/counsel/controller/CounselController.java
  src/main/java/com/backend/dorandoran/counsel/domain/entity/Counsel.java
  src/main/java/com/backend/dorandoran/counsel/domain/response/CounselHistoryResponse.java
  src/main/java/com/backend/dorandoran/counsel/repository/DialogRepository.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselChatService.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselResultService.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselService.java
  src/main/java/com/backend/dorandoran/counsel/service/python/EndCounsel.py
  src/main/java/com/backend/dorandoran/counsel/service/python/LangChain.py
  src/main/java/com/backend/dorandoran/counsel/service/python/LangChainEntireDialog.py
Labels: :sparkles: feature, :recycle: refactor

#51 fix: counsel history date
  src/main/java/com/backend/dorandoran/common/domain/BaseDateTimeEntity.java
  src/main/java/com/backend/dorandoran/counsel/domain/entity/Counsel.java
  src/main/java/com/backend/dorandoran/counsel/domain/response/CounselHistoryResponse.java
  src/main/java/com/backend/dorandoran/counsel/repository/DialogRepository.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselChatService.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselService.java
Labels: :bug: bug

#52 Feature/sign out
  src/main/java/com/backend/dorandoran/assessment/repository/UserMentalStateRepository.java
  src/main/java/com/backend/dorandoran/user/repository/querydsl/UserQueryRepository.java
  src/main/java/com/backend/dorandoran/user/repository/querydsl/UserQueryRepositoryImpl.java
Labels: :bug: bug, :recycle: refactor

#54 style: gpt config
  src/main/java/com/backend/dorandoran/config/GptConfig.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselChatService.java
Labels: :recycle: refactor

#55 Refactor/python to java
  src/main/java/com/backend/dorandoran/counsel/service/CounselChatService.java
  src/main/java/com/backend/dorandoran/user/domain/entity/UserMentalState.java
Labels: :bug: bug, :sparkles: feature

#56 Refactor
  src/main/java/com/backend/dorandoran/counsel/domain/response/CounselHistoryResponse.java
  src/main/java/com/backend/dorandoran/counsel/repository/CounselQueryRepository.java
  src/main/java/com/backend/dorandoran/counsel/repository/CounselQueryRepositoryImpl.java
  src/main/java/com/backend/dorandoran/counsel/repository/CounselRepository.java
  src/main/java/com/backend/dorandoran/counsel/repository/DialogRepository.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselChatService.java
  src/main/java/com/backend/dorandoran/counsel/service/CounselService.java
Labels: :recycle: refactor

#59 counselDate to date
  src/main/java/com/backend/dorandoran/counsel/repository/CounselQueryRepositoryImpl.java
  src/main/java/com/backend/dorandoran/mypage/domain/response/CompletedCounselResponse.java
  src/main/java/com/backend/dorandoran/mypage/repository/MypageQueryRepositoryImpl.java
Labels: :recycle: refactor
